#!/usr/bin/env bun
/**
 * download-channel.ts
 *
 * Downloads every file from a Telegram channel, then bundles them into
 * ≤ 90 MB zip archives written to ../downloads/<channel_id>/.
 *
 * Required env vars
 * ─────────────────
 *   TG_API_ID      – Telegram API ID   (https://my.telegram.org)
 *   TG_API_HASH    – Telegram API hash
 *   TG_SESSION     – Session string generated by create-session.ts
 *   TG_CHANNEL_ID  – Target channel ID, e.g. -1001234567890
 */

import { TelegramClient } from '@mtcute/bun';
import fs from 'fs';
import path from 'path';

// ── Constants ─────────────────────────────────────────────────────────────────

/** Maximum *uncompressed* bytes to pack into one zip part. */
const MAX_PART_BYTES = 90 * 1024 * 1024; // 90 MB

// ── Structured logger ─────────────────────────────────────────────────────────

const colors = {
  reset: '\x1b[0m',
  dim: '\x1b[2m',
  cyan: '\x1b[36m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  bold: '\x1b[1m',
};

function timestamp(): string {
  return new Date().toISOString();
}

const log = {
  step: (msg: string) =>
    console.log(`${colors.dim}[${timestamp()}]${colors.reset} ${colors.bold}${colors.cyan}── ${msg}${colors.reset}`),

  info: (msg: string, ...rest: unknown[]) =>
    console.log(`${colors.dim}[${timestamp()}]${colors.reset} ℹ️  ${msg}`, ...rest),

  ok: (msg: string, ...rest: unknown[]) =>
    console.log(`${colors.dim}[${timestamp()}]${colors.reset} ${colors.green}✔${colors.reset}  ${msg}`, ...rest),

  warn: (msg: string, ...rest: unknown[]) =>
    console.warn(`${colors.dim}[${timestamp()}]${colors.reset} ${colors.yellow}⚠${colors.reset}  ${msg}`, ...rest),

  error: (msg: string, ...rest: unknown[]) =>
    console.error(`${colors.dim}[${timestamp()}]${colors.reset} ${colors.red}✖${colors.reset}  ${msg}`, ...rest),

  rule: () => console.log(`${colors.dim}${'─'.repeat(70)}${colors.reset}`),
};

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Strip characters that are unsafe in filenames. */
function safeFilename(raw: string): string {
  return raw
    .replace(/[/\\?%*:|"<>\x00-\x1f]/g, '_')
    .replace(/_{2,}/g, '_')
    .slice(0, 240);
}

/** Human-readable byte size. */
function humanBytes(n: number): string {
  if (n < 1_024) return `${n} B`;
  if (n < 1_048_576) return `${(n / 1_024).toFixed(1)} KB`;
  if (n < 1_073_741_824) return `${(n / 1_048_576).toFixed(1)} MB`;
  return `${(n / 1_073_741_824).toFixed(2)} GB`;
}

/**
 * Resolve a unique path inside a directory.
 * If `name` already exists, appends _1, _2, … until a free slot is found.
 */
function uniquePath(dir: string, name: string): string {
  let candidate = path.join(dir, name);
  if (!fs.existsSync(candidate)) return candidate;

  const ext = path.extname(name);
  const base = path.basename(name, ext);
  let i = 1;
  do {
    candidate = path.join(dir, `${base}_${i}${ext}`);
    i++;
  } while (fs.existsSync(candidate));
  return candidate;
}

// ── Config ────────────────────────────────────────────────────────────────────

const API_ID = parseInt(process.env.TG_API_ID ?? '', 10);
const API_HASH = process.env.TG_API_HASH ?? '';
const SESSION = process.env.TG_SESSION ?? '';
const CHANNEL = process.env.TG_CHANNEL_ID ?? '';

if (!API_ID || !API_HASH || !SESSION || !CHANNEL) {
  log.error('Missing required env vars. Set: TG_API_ID, TG_API_HASH, TG_SESSION, TG_CHANNEL_ID');
  process.exit(1);
}

const CHANNEL_ID = parseInt(CHANNEL, 10);
if (Number.isNaN(CHANNEL_ID)) {
  log.error(`TG_CHANNEL_ID "${CHANNEL}" is not a valid integer.`);
  process.exit(1);
}

// Paths are relative to the repo root (scripts/../)
const SCRIPT_DIR = import.meta.dir;
const DOWNLOADS_DIR = path.resolve(SCRIPT_DIR, '..', 'downloads', CHANNEL);
const TMP_DIR = path.resolve(SCRIPT_DIR, '..', '.tmp_tg', CHANNEL);

fs.mkdirSync(DOWNLOADS_DIR, { recursive: true });
fs.mkdirSync(TMP_DIR, { recursive: true });

// ── Banner ────────────────────────────────────────────────────────────────────

log.rule();
log.step('Telegram Channel Downloader');
log.info(`Channel ID  : ${CHANNEL_ID}`);
log.info(`Output dir  : ${DOWNLOADS_DIR}`);
log.info(`Temp dir    : ${TMP_DIR}`);
log.info(`Max zip size: ${humanBytes(MAX_PART_BYTES)}`);
log.rule();

// ── Connect to Telegram ───────────────────────────────────────────────────────

log.step('Connecting to Telegram…');

const tg = new TelegramClient({ apiId: API_ID, apiHash: API_HASH });
await tg.importSession(SESSION);

await tg.start({
  // These callbacks are only invoked when the session string is expired/invalid.
  phone: () => {
    log.error('Session is invalid or expired. Run create-session.ts to generate a fresh one.');
    process.exit(1);
  },
  code: () => {
    process.exit(1);
  },
});

const me = await tg.getMe();
const identity = me.username
  ? `@${me.username}`
  : `${me.firstName ?? ''}${me.lastName ? ' ' + me.lastName : ''}`.trim() || String(me.id);

log.ok(`Authenticated as ${identity} (id: ${me.id})`);

// ── Iterate messages & download ───────────────────────────────────────────────

log.step('Scanning channel messages and downloading files…');
log.info('(This may take a while for large channels)');
log.rule();

interface FileEntry {
  name: string;
  tmpPath: string;
  size: number;
}

const downloaded: FileEntry[] = [];
let msgCount = 0;
let skipCount = 0;

for await (const msg of await tg.getHistory(CHANNEL_ID, { limit: 1_000_000 })) {
  msgCount++;

  const media = msg.media;
  if (!media) continue;

  // ── Derive a filename based on media type ──────────────────────────────
  let rawName: string;

  switch (media.type) {
    case 'document':
      rawName = media.fileName || `doc_${msg.id}`;
      // Append extension from MIME if the filename has none
      if (!path.extname(rawName) && media.mimeType) {
        const sub = media.mimeType.split('/')[1];
        if (sub && !sub.includes(';')) rawName += `.${sub}`;
      }
      break;

    case 'photo':
      rawName = `photo_${msg.id}.jpg`;
      break;

    case 'audio':
      rawName = media.fileName || `audio_${msg.id}.mp3`;
      break;

    case 'video':
      rawName = media.fileName || `video_${msg.id}.mp4`;
      break;

    default:
      // Skip unsupported media types (polls, geo, contacts, etc.)
      skipCount++;
      continue;
  }

  const filename = safeFilename(rawName);
  const destPath = uniquePath(TMP_DIR, filename);

  log.info(`[msg ${String(msg.id).padStart(8)}] ↓ ${filename} — ${colors.dim}${media.type}${colors.reset}`);

  try {
    await tg.downloadToFile(destPath, media);
    const size = fs.statSync(destPath).size;
    downloaded.push({ name: path.basename(destPath), tmpPath: destPath, size });
    log.ok(`  ${path.basename(destPath)} (${humanBytes(size)})`);
  } catch (err) {
    log.warn(`  Failed to download "${filename}": ${err}`);
    // Clean up any partial file
    if (fs.existsSync(destPath)) fs.unlinkSync(destPath);
  }
}

await tg.destroy();

log.rule();
log.ok(`Messages scanned : ${msgCount}`);
log.ok(`Files downloaded : ${downloaded.length}`);
log.info(`Media skipped   : ${skipCount} (non-file types)`);
log.rule();

if (downloaded.length === 0) {
  log.warn('No downloadable files found in channel. Exiting.');
  process.exit(0);
}

// ── Cleanup ───────────────────────────────────────────────────────────────────

log.step('Cleaning up temp directory…');
fs.rmSync(TMP_DIR, { recursive: true, force: true });
log.ok('Temp directory removed.');

// ── Summary ───────────────────────────────────────────────────────────────────

log.rule();
log.info(`  ${DOWNLOADS_DIR}`);
log.rule();

log.rule();
